version: "3.8"

services:

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE : "${MYSQL_DATABASE}"
      MYSQL_USER : "${MYSQL_USER}"
      MYSQL_PASSWORD : "${MYSQL_PASSWORD}"
    volumes:
      - db:/var/lib/mysql/
    networks:
      - test  

  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - test   

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE : "${MYSQL_DATABASE}"
      MYSQL_USER : "${MYSQL_USER}"
      MYSQL_PASSWORD : "${MYSQL_PASSWORD}"
      MYSQL_HOST : "${MYSQL_HOST}"
    volumes:
      - wp:/var/www/html
    networks:
      - test 

volumes:
 wp:
  driver: local #volume is located locally
  driver_opts:
   o: bind #binding the volume
   type: none #setting the type of volume
   device: /Users/abba/codam_project/inception/wordpress #setting the directory of volume
 db:
  driver: local #volume is located locally
  driver_opts:
    o: bind #binding the volume
    type: none #setting the type of volume
    device: /Users/abba/codam_project/inception/db #setting the directory of volume
networks:
  test:
    driver: bridge