CREATE DATABASE IF NOT EXISTS db;

GRANT ALL PRIVILEGES ON db.* TO 'ab'@'localhost' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'ab'@'localhost' IDENTIFIED BY 'ab';
CREATE USER IF NOT EXISTS 'ab1'@'localhost' IDENTIFIED BY 'ab1';
FLUSH PRIVILEGES;