CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS "ab"@"%" IDENTIFIED BY "12345";
ALTER USER "ab"@"%" IDENTIFIED BY "12345";
GRANT ALL PRIVILEGES ON * . * TO "ab"@"%" IDENTIFIED by "12345";
FLUSH PRIVILEGES;